// @generated by `ruskel-snapshot`; do not edit.
//
// Package: luau-analyze
// Publish: crates.io
// Workspace dependencies: none
// Workspace dependents: lan, xtask

//! In-process Luau type checking for Rust.
//!
//! # Example
//!
//! ```no_run
//! use luau_analyze::Checker;
//!
//! let mut checker = Checker::new().expect("checker should initialize");
//! checker
//!     .add_definitions(
//!         r#"
//!         declare class TodoBuilder
//!             function content(self, content: string): TodoBuilder
//!         end
//!         declare Todo: { create: () -> TodoBuilder }
//!         "#,
//!     )
//!     .expect("definitions should load");
//!
//! let result = checker.check(
//!     r#"
//!     --!strict
//!     local _todo = Todo.create():content("review")
//!     "#,
//! );
//! assert!(result.is_ok());
//! ```

use std::{
    fmt::{Debug, Display},
    path::Path,
    time::Duration,
};

/// A reusable cancellation token that can be signaled from another thread.
///
/// `CancellationToken` is `Send` and `Sync` because the underlying Luau
/// implementation uses atomic operations to manage its signaled state safely
/// across thread boundaries.
#[derive(Clone, Debug)]
pub struct CancellationToken {/* private fields */}

impl CancellationToken {
    /// Requests cancellation on this token.
    pub fn cancel(&self);

    /// Creates a new cancellation token.
    pub fn new() -> Result<Self, Error>;

    /// Clears cancellation state on this token.
    pub fn reset(&self);
}

/// Per-call options for `Checker::check_with_options`.
#[derive(Clone, Copy, Debug, Default)]
pub struct CheckOptions<'a> {
    /// Optional timeout override for this call.
    pub timeout: Option<Duration>,
    /// Optional module label override for this call.
    ///
    /// For source that uses relative `require(...)`, this must identify a real
    /// filesystem module path so the checker can resolve adjacent files.
    pub module_name: Option<&'a str>,
    /// Optional cancellation token for this call.
    pub cancellation_token: Option<&'a CancellationToken>,
    /// Optional host-provided virtual modules visible to this call.
    pub virtual_modules: &'a [VirtualModule<'a>],
}

/// Result of a single checker run.
#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct CheckResult {
    /// Collected diagnostics sorted by location and severity.
    pub diagnostics: Vec<Diagnostic>,
    /// Whether the check hit one or more time limits.
    pub timed_out: bool,
    /// Whether cancellation was requested during checking.
    pub cancelled: bool,
}

impl CheckResult {
    /// Returns all error diagnostics.
    pub fn errors(&self) -> Vec<&Diagnostic>;

    /// Returns `true` when the result contains one or more errors.
    pub fn has_errors(&self) -> bool;

    /// Returns `true` when the result contains one or more warnings.
    pub fn has_warnings(&self) -> bool;

    /// Returns `true` when the result contains no errors.
    pub fn is_ok(&self) -> bool;

    /// Returns all warning diagnostics.
    pub fn warnings(&self) -> Vec<&Diagnostic>;
}

/// Reusable checker instance with persistent global definitions.
///
/// `Checker` is `Send` but not `Sync`. The underlying Luau Analysis structures
/// are safely movable between threads, but all operations that mutate or read
/// from the checker require exclusive `&mut self` access, meaning it cannot
/// be concurrently accessed from multiple threads.
#[derive(Send)]
pub struct Checker {/* private fields */}

impl Checker {
    /// Loads Luau definition source using default module label.
    pub fn add_definitions(&mut self, defs: &str) -> Result<(), Error>;

    /// Loads Luau definitions from a UTF-8 text file using the path as module
    /// label.
    pub fn add_definitions_path(&mut self, path: &Path) -> Result<(), Error>;

    /// Loads Luau definition source with an explicit module label.
    pub fn add_definitions_with_name(&mut self, defs: &str, module_name: &str)
    -> Result<(), Error>;

    /// Type-checks a Luau source module with default options.
    pub fn check(&mut self, source: &str) -> Result<CheckResult, Error>;

    /// Type-checks a Luau source file with default options and the path as
    /// module label.
    pub fn check_path(&mut self, path: &Path) -> Result<CheckResult, Error>;

    /// Type-checks a Luau source file with explicit per-call options.
    ///
    /// Relative `require(...)` calls are resolved against the file path unless
    /// `options.module_name` overrides it with a different module label.
    pub fn check_path_with_options(
        &mut self,
        path: &Path,
        options: CheckOptions<'_>,
    ) -> Result<CheckResult, Error>;

    /// Type-checks a Luau source module with explicit per-call options.
    pub fn check_with_options(
        &mut self,
        source: &str,
        options: CheckOptions<'_>,
    ) -> Result<CheckResult, Error>;

    /// Creates a checker with default options.
    pub fn new() -> Result<Self, Error>;

    /// Returns immutable access to default checker options.
    pub fn options(&self) -> &CheckerOptions;

    /// Creates a checker with explicit defaults.
    pub fn with_options(options: CheckerOptions) -> Result<Self, Error>;
}

impl Drop for Checker {}

impl !Sync for Checker {}

/// Default checker configuration used by `Checker`.
#[derive(Clone, Debug, Default)]
pub struct CheckerOptions {
    /// Optional timeout applied to checks that do not override it.
    pub default_timeout: Option<Duration>,
    /// Default module label used for source checks.
    pub default_module_name: String,
    /// Default module label used for definition loading.
    pub default_definitions_module_name: String,
}

/// Stable checker policy values exposed by this crate.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct CheckerPolicy {
    /// Whether strict mode is always enforced.
    pub strict_mode: bool,
    /// Active solver policy string.
    pub solver: &'static str,
    /// Whether batch queue support is exposed by this crate.
    pub exposes_batch_queue: bool,
}

/// A single diagnostic item from checking Luau source.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Diagnostic {
    /// Zero-based start line.
    pub line: u32,
    /// Zero-based start column.
    pub col: u32,
    /// Zero-based end line.
    pub end_line: u32,
    /// Zero-based end column.
    pub end_col: u32,
    /// Severity level.
    pub severity: Severity,
    /// Human-readable diagnostic message.
    pub message: String,
}

/// One parameter extracted from a direct functional entrypoint.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct EntrypointParam {
    /// Parameter name in source order.
    pub name: String,
    /// Type annotation text as written.
    pub annotation: String,
    /// Whether the parameter is syntactically optional.
    pub optional: bool,
}

/// Parsed schema for a direct `return function(...) ... end` chunk.
#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct EntrypointSchema {
    /// Ordered parameter list for the returned function literal.
    pub params: Vec<EntrypointParam>,
}

/// Errors returned by checker construction and definition loading.
#[derive(Clone, Debug, Display, Eq, PartialEq, std::error::Error)]
pub enum Error {
    /// The private native checker library could not be loaded.
    NativeLibrary(String),
    /// Checker creation failed in the native layer.
    CreateCheckerFailed,
    /// Cancellation token creation failed in the native layer.
    CreateCancellationTokenFailed,
    /// Definitions failed to parse or type-check.
    Definitions(String),
    /// Entrypoint schema extraction failed.
    EntrypointSchema(String),
    /// Reading a UTF-8 text file failed before checking or loading definitions.
    ReadFile {
        /// Logical input category such as `"source"` or `"definitions"`.
        kind: &'static str,
        /// Display label for the file path.
        path: String,
        /// Human-readable I/O error message.
        message: String,
    },
    /// UTF-8 input is too large for the C ABI length type.
    InputTooLarge {
        /// Logical input category such as `"source"` or `"definitions"`.
        kind: &'static str,
        /// Original input length in bytes.
        len: usize,
    },
}

/// Diagnostic severity emitted by the checker.
#[derive(Clone, Copy, Debug, Eq, Ord, PartialEq, PartialOrd)]
pub enum Severity {
    /// Type-check or lint error.
    Error,
    /// Lint warning.
    Warning,
}

impl Severity {
    /// Returns the severity as a stable lowercase string.
    pub const fn as_str(self) -> &'static str;
}

/// One host-provided virtual module visible to a single check.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct VirtualModule<'a> {
    /// Module name used by `require(...)`, for example `"term"`.
    pub name: &'a str,
    /// Source code returned by the host for that module.
    pub source: &'a str,
}

/// Returns the current fixed checker policy.
pub const fn checker_policy() -> CheckerPolicy;

/// Extracts parameter names, annotation text, and optionality from a direct
/// `return function(...) ... end` chunk.
pub fn extract_entrypoint_schema(source: &str) -> Result<EntrypointSchema, Error>;
